version: '2'

services:
  webce:
    build:
      context: .
      args:
        - GITHUB_TOKEN
    environment:
      - APP_HOSTNAME=dockerm1demo_webce.docker
      - PUBLIC_ADDRESS=https://dockerm1demo_webce.docker/
      - APP_USER_LOCAL=true
      - DATABASE_HOST=database
      - DATABASE_NAME=magentodb
      - DATABASE_USER=magento
      - DATABASE_PASSWORD=magento
      - DATABASE_ROOT_PASSWORD=magento
      - MAGENTO_CRYPT_KEY=VElJzTQztEttxRfSyVn5w4sAqOjWvWFa
      - FORCE_DATABASE_DROP=false
      - GITHUB_TOKEN
    links:
      - database
      - redis
      - memcached
    expose:
      - 80
      - 443

  database:
    image: quay.io/continuouspipe/mysql5.6:v1.0
    environment:
      MYSQL_ROOT_PASSWORD: magento
      MYSQL_DATABASE: magentodb
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento

  redis:
    image: quay.io/continuouspipe/redis3:v1.0

  memcached:
    image: quay.io/continuouspipe/memcached1.4:v1.0

